version: '3.8'

services:
  app:
    build: .
    image: crux-web-socket:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - app-network

  # ... your kafka and zookeeper services ...

networks:
  app-network:
    driver: bridge